enyo.depends(
	"$lib/layout",
	"$lib/onyx",
	"$lib/scoreit-api",
	"css/",
	"SelectDecorator/",
	"ReportPrepView.js",
	"SignUpView.js",
	"FormField.js",
	"CreateTeamView.js",
	"FilteredSelector.js",
	"EditClubView.js",
	"FilteredList.js",
	"TextFieldSelector.js"
);
