enyo.depends(
	"$lib/layout",
	"$lib/onyx",
	"$lib/scoreit-api",
	"css/",
	"SelectDecorator/",
	"ReportPrepView.js",
	"SignUpView.js",
	"FormField.js",
	"EditTeamView.js",
	"FilteredSelector.js",
	"EditClubView.js",
	"FilteredList.js",
	"TextFieldSelector.js",
	"EditProfileView.js",
	"LoginView.js",
	"FrontMatter.js"
);
